name: Node.js CI

# Créer une pipeline pour automatiser le lancement des tests lorsqu'une PR est validée depuis une branche `feature/<nom_feature>` vers la branche `develop`.
# Elle testera l'application sur les versions 14 et 15 de node uniquement.

on:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  build:
    if:  startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:coverage > coverage.txt
      - name: upload artefact
        with:
          name: coverage
          path: coverage.txt
